spring:
  application:
    name: encryption
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    mongodb:
      username: myappuser
      password: mypassword
      database: myappdb
      host: localhost
      port: 27017
